In [1]:
import pandas as pd
import numpy as np
from backtesting import Backtest, Strategy
import os 
import source.stock_load as loader
from source.stock_features import *
from source.stock_preparation import * 
from source.stock_strategy import *
from source.stock_risk import *
from source.stock_backtest import *
from source.stock_performance import *

c:\Users\Hello!!!\AppData\Local\Programs\Python\Python313\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
c:\Users\Hello!!!\AppData\Local\Programs\Python\Python313\Lib\site-packages\backtesting\_plotting.py:55: UserWarning: Jupyter Notebook detected. Setting Bokeh output to notebook. This may not work in Jupyter clients without JavaScript support, such as old IDEs. Reset with `backtesting.set_bokeh_output(notebook=False)`.
  warnings.warn('Jupyter Notebook detected. '

In [2]:
data = loader.load_local_data()

 Đang đọc dữ liệu từ đĩa: data/stock_data_70.csv...
Đã đọc dữ liệu thành công.

In [3]:
data.head(5)

                        Open       High        Low      Close  Adj Close  \
Date       Ticker
2015-01-02 AAPL    27.847500  27.860001  26.837500  27.332500  24.237556
           ABBV    65.440002  66.400002  65.440002  65.889999  42.091431
           ADBE    72.699997  73.199997  71.889999  72.339996  72.339996
           AEP     60.880001  61.240002  60.389999  61.150002  41.371323
           AMD      2.670000   2.670000   2.670000   2.670000   2.670000

                      Volume
Date       Ticker
2015-01-02 AAPL    212818400
           ABBV      5086100
           ADBE      2349200
           AEP       2007400
           AMD             0

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
MultiIndex: 189140 entries, (Timestamp('2015-01-02 00:00:00'), 'AAPL') to (Timestamp('2025-09-30 00:00:00'), 'XOM')
Data columns (total 6 columns):
 #   Column     Non-Null Count   Dtype
---  ------     --------------   -----
 0   Open       189140 non-null  float64
 1   High       189140 non-null  float64
 2   Low        189140 non-null  float64
 3   Close      189140 non-null  float64
 4   Adj Close  189140 non-null  float64
 5   Volume     189140 non-null  int64
dtypes: float64(5), int64(1)
memory usage: 9.3+ MB

In [5]:
train_data, test_data = split_simple_train_test(data,0.8)

In [ ]:
train_result = full_run_simple_backtest(train_data, strategy_name ="breakout")

In [7]:
result = full_get_trade_performance_metrics(train_result,total_test_bars= len(train_data))

In [8]:
result

,Ticker,1. Gross Gain,2. Gross Loss,3. Net Profit,4. % Time in Market,5. Number of Trades,6. Annual Turnover,7. Hit Rate,8. Profit Factor,9. Avg Gain (Wins),10. Avg Loss (Losses),11. Slugging Ratio
0,AAPL,1.400907e+08,5.948015e+07,8.061052e+07,0.010739,78,0.13,48.72%,2.36,8.60%,3.48%,2.47
1,TSLA,1.487909e+08,8.115881e+07,6.763212e+07,0.009563,87,0.14,39.08%,1.83,21.29%,7.13%,2.99
2,SLB,1.220698e+08,6.439743e+07,5.767239e+07,0.009913,87,0.14,47.13%,1.90,8.50%,4.18%,2.03
3,PFE,1.352308e+08,8.451250e+07,5.071825e+07,0.010151,88,0.15,40.91%,1.60,6.26%,2.98%,2.10
4,COP,1.200741e+08,8.066455e+07,3.940952e+07,0.009913,87,0.14,34.48%,1.49,10.98%,4.59%,2.39
...,...,...,...,...,...,...,...,...,...,...,...,...
65,CCI,6.084926e+07,1.155356e+08,-5.468635e+07,0.010125,104,0.17,24.04%,0.53,5.11%,3.35%,1.53
66,JNJ,6.578200e+07,1.207812e+08,-5.499923e+07,0.009880,110,0.18,30.91%,0.54,2.99%,2.44%,1.22
67,TMUS,6.333835e+07,1.207806e+08,-5.744224e+07,0.009801,113,0.19,27.43%,0.52,4.29%,3.82%,1.12
68,ECL,5.548840e+07,1.168030e+08,-6.131463e+07,0.009510,104,0.17,28.85%,0.48,4.26%,3.30%,1.29
69,UNH,4.565082e+07,1.316521e+08,-8.600132e+07,0.009642,110,0.18,27.27%,0.35,3.95%,3.69%,1.07

In [11]:
result[result['3. Net Profit']>0]

,Ticker,1. Gross Gain,2. Gross Loss,3. Net Profit,4. % Time in Market,5. Number of Trades,6. Annual Turnover,7. Hit Rate,8. Profit Factor,9. Avg Gain (Wins),10. Avg Loss (Losses),11. Slugging Ratio
0,AAPL,1.400907e+08,5.948015e+07,8.061052e+07,0.010739,78,0.13,48.72%,2.36,8.60%,3.48%,2.47
1,TSLA,1.487909e+08,8.115881e+07,6.763212e+07,0.009563,87,0.14,39.08%,1.83,21.29%,7.13%,2.99
2,SLB,1.220698e+08,6.439743e+07,5.767239e+07,0.009913,87,0.14,47.13%,1.90,8.50%,4.18%,2.03
3,PFE,1.352308e+08,8.451250e+07,5.071825e+07,0.010151,88,0.15,40.91%,1.60,6.26%,2.98%,2.10
4,COP,1.200741e+08,8.066455e+07,3.940952e+07,0.009913,87,0.14,34.48%,1.49,10.98%,4.59%,2.39
5,AMD,1.234750e+08,8.410479e+07,3.937019e+07,0.009927,90,0.15,42.22%,1.47,15.46%,8.38%,1.85
6,GE,1.142357e+08,7.688034e+07,3.735538e+07,0.009576,88,0.15,35.23%,1.49,10.77%,3.34%,3.22
7,NVDA,1.209087e+08,8.618853e+07,3.472013e+07,0.010482,93,0.15,36.56%,1.40,14.53%,5.36%,2.71
8,BA,1.263044e+08,9.709326e+07,2.921114e+07,0.009504,92,0.15,32.61%,1.30,12.22%,4.47%,2.73
9,MPC,1.024988e+08,7.360703e+07,2.889178e+07,0.010006,88,0.15,44.32%,1.39,10.08%,4.61%,2.19
10,CAT,9.708372e+07,7.666233e+07,2.042139e+07,0.009675,92,0.15,46.74%,1.27,5.37%,4.04%,1.33
11,AMZN,9.602175e+07,7.612759e+07,1.989417e+07,0.010125,88,0.15,39.77%,1.26,7.42%,3.72%,1.99
12,FCX,1.094596e+08,9.321135e+07,1.624826e+07,0.009285,94,0.16,35.11%,1.17,15.15%,7.03%,2.16
13,NFLX,1.160300e+08,1.041275e+08,1.190247e+07,0.009431,105,0.17,33.33%,1.11,10.37%,5.82%,1.78
14,NUE,1.110891e+08,1.006073e+08,1.048178e+07,0.010389,99,0.16,33.33%,1.10,9.42%,4.70%,2.00
15,COST,9.824884e+07,8.897344e+07,9.275400e+06,0.009973,96,0.16,33.33%,1.10,5.48%,2.62%,2.09
16,XOM,1.155461e+08,1.064955e+08,9.050677e+06,0.009966,99,0.16,30.30%,1.08,7.77%,3.55%,2.19
17,BAC,9.954389e+07,9.266109e+07,6.882800e+06,0.009814,96,0.16,37.50%,1.07,6.89%,3.87%,1.78
18,ADBE,8.344854e+07,7.719026e+07,6.258281e+06,0.010376,81,0.13,40.74%,1.08,7.14%,4.27%,1.67
19,AVGO,1.039555e+08,9.969393e+07,4.261548e+06,0.009993,102,0.17,34.31%,1.04,8.36%,4.05%,2.06
20,AEP,9.430194e+07,9.040091e+07,3.901028e+06,0.010237,95,0.16,34.74%,1.04,4.53%,2.62%,1.73
21,SHW,9.653884e+07,9.324176e+07,3.297081e+06,0.009332,90,0.15,41.11%,1.04,5.95%,3.91%,1.52
22,LLY,1.154759e+08,1.130590e+08,2.416869e+06,0.010297,102,0.17,32.35%,1.02,6.92%,3.90%,1.78
23,ABBV,1.076266e+08,1.063089e+08,1.317699e+06,0.009616,93,0.15,31.18%,1.01,7.76%,3.71%,2.09

In [10]:
a = calculate_full_portfolio_performance(train_result)
df = pd.DataFrame([a])
df

,total_test_bars,avg_daily_return,annual_avg_return,annual_geo_return,daily_vol,annual_vol,max_drawdown,sharpe_ratio,calmar_ratio,hit_rate,profit_factor,long_cum_return
0,2162,-0.000004,-0.001058,-0.001065,0.000247,0.00392,-0.012819,-0.269884,-0.082522,0.490287,0.944505,-0.0091